apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: daas-hpa
  labels:
    app: daas
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: daas
  minReplicas: 1
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50
