apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
data:
  POSTGRES_DB: postgres # base64 encoded value of 'mydatabase'
  POSTGRES_USER: postgres # base64 encoded value of 'myuser'
  POSTGRES_PASSWORD: X1g0y^M13KF@J43 # base64 encoded value of 'mypassword'
